# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: gps_dev
 pool: 5
 username: root
 password: 'abc123'
 socket: /var/run/mysqld/mysqld.sock
test:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: gps_test
 pool: 5
 username: root
 password: 'abc123'
 socket: /var/run/mysqld/mysqld.sock
production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: gps_prod
 pool: 5
 username: root
 password: 'abc123'
 socket: /var/run/mysqld/mysqld.sock
